### ISSUE TITLE
gulp-zip isn't installed automatically

### ISSUE THREAD

**Issue by steckdev** [willyg302/gulp-awslambda#14]
I went to use the tool and I need to install gulp-zip you might just add that to the config file.

**Comment by nickcoury** [comment]
`gulp-awslambda` doesn't require `gulp-zip`, which is why it isn't included in `package.json`.  For example, if you just wanted to upload a single handler file, you could do so without needing to create a zip file.

The example shows how easy it is to use `gulp-zip`. If you follow it you'll need to add that dependency as you mention you have, but that's no different than `gulp` itself needing to be added (which is also in the example`.

**Comment by willyg302** [comment]
The comment by @nickcoury is correct; following Gulp's composability style the step of transforming your build artifacts into a .zip is up to you.
